# Refer to https://wiki.hypr.land/Configuring/Basics/Variables/

# Variables
$activeBorderColor = rgba(89b4faee)
$inactiveBorderColor = rgba(595959aa)

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    gaps_in = 0
    gaps_out = 0

    border_size = 0

    # https://wiki.hypr.land/Configuring/Basics/Variables/#variable-types for info about colors
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
    allow_tearing = false

    # Change to niri-like side-scrolling layout
    layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.15

    shadow {
        enabled = true
        range = 2
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Basics/Variables/#blur
    blur {
        enabled = true
        size = 2
        passes = 2
    }
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#group
group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    enabled = no
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    column_width = 0.97
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering  = true
    disable_scale_notification = true
    focus_on_activate = true
    anr_missed_pings = 3
    on_focus_under_fullscreen = 1
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#cursor
cursor {
    hide_on_key_press = true
    warp_on_change_workspace = 1
}

# Auto toggle scratchpad on switching workspace from scratchpad
binds {
    hide_special_on_workspace_change = true
}
